version: "3.8"

services:
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'   # Porta HTTP padrão
      - '81:81'   # Porta do Painel de Administração do Nginx
      - '443:443' # Porta HTTPS padrão
    volumes:
      - nginx_data:/data
      - nginx_letsencrypt:/etc/letsencrypt
    networks:
      - cronos_net

  api.cronosbot:
    image: ${DOCKER_REGISTRY-}apicronosbot
    build:
      context: .
      dockerfile: Api.CronosBot/Dockerfile
    ports:
      - "8085:8080"
    restart: always
    environment:
      - ConnectionStrings__Connection=Host=postgres_db;Port=5432;Database=evolution_db;Username=postgres;Password=postgresadmin
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Production
      - EvolutionApi__ApiKey=a8f3c7d2-61b5-4e9a-bc04-83e215d74f69
      - EvolutionApi__BaseUrl=http://evolution-api:8083
      - TZ=America/Sao_Paulo
    networks:
      - cronos_net
    depends_on:
      postgres_db:
        condition: service_healthy 
      evolution-api:
        condition: service_started

  evolution-api:
    image: evoapicloud/evolution-api:latest
    restart: always
    environment:
      - SERVER_URL=https://evo.botcronos.com.br 
      - ENV=prod 
      - API_KEY=a8f3c7d2-61b5-4e9a-bc04-83e215d74f69
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_CLIENT=pg
      - DATABASE_CONNECTION_URI=postgresql://postgres:postgresadmin@postgres_db:5432/evolution_db?schema=public
      - AUTHENTICATION_API_KEY=a8f3c7d2-61b5-4e9a-bc04-83e215d74f69
      - CACHE_REDIS_ENABLED=false
      - CACHE_LOCAL_ENABLED=true
      - LOG_LEVEL=ERROR,WARN 
    ports:
      - "8083:8083"
    networks:
      - cronos_net
    volumes:
      - evolution_instances:/evolution/instances
    depends_on:
      postgres_db:
        condition: service_healthy

  postgres_db:
    image: pgvector/pgvector:pg15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresadmin
      - POSTGRES_DB=evolution_db
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d evolution_db"] 
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cronos_net
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  cronos_net:
    driver: bridge

volumes:
  evolution_instances:
  postgres_data:
  nginx_data:        
  nginx_letsencrypt: 